baseurl         = ""
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
publishDir = "docs"

[params]
  title       = "Thoughts of a Curious Mind"
  subtitle    = "Welcome, friend."

  cover       = "uploads/purple_background.jpeg"
  description = "The place where I express my opinion."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "RbnLcmb"
  githubName = "robinlacombe"

  logo = ""
  orgName = "RL"
  orgWebsite = "https://www.robinlacombe.com"
  orgDescription = "Here is a description placeholder for your org"

  author = "RL"
  authorAvatar = "uploads/profile-picture.jpg"
  authorLocation = ""
  authorDescription = "Curious Mind"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Freedom"
  url = "/categories/freedom/"
  weight = 100

[[menu.main]]
  name = "Knowledge"
  url = "/categories/knowledge/"
  weight = 99

[[menu.main]]
  name = "Tutorials"
  url = "/categories/tutorials"
  weight = 95